development: &postgres
  adapter: postgresql
  encoding: unicode
  database: beebuzz_dev
  pool: 25
  username: postgres
  password: postgres
  host: 10.0.2.2
  port: 5432

test:
  <<: *postgres

production:
  <<: *postgres

staging:
  <<: *postgres